name: numida

services:
  server:
    build:
      context: .
    ports:
      - 2024:5000

  test:
    build:
      context: .
    command: python -m unittest test_app.py -v
    profiles:
      - test
